# -*- coding: utf-8 -*-
"""run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3QheykxcV_I3B9SM-lBNODd_4bv4yqV
"""

from flask import Flask
from app.routes import main

app = Flask(__name__)
app.register_blueprint(main)

application = app

if __name__ == "__main__":
    app.run(debug=True)