# -*- coding: utf-8 -*-
"""_init__

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3QheykxcV_I3B9SM-lBNODd_4bv4yqV
"""

from flask import Flask
from app.db import db

def create_app():
    app = Flask(__name__)
    return app