# -*- coding: utf-8 -*-
"""db

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3QheykxcV_I3B9SM-lBNODd_4bv4yqV
"""

from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()