# -*- coding: utf-8 -*-
"""run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3QheykxcV_I3B9SM-lBNODd_4bv4yqV
"""

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# Initialize scaler and model
scaler = StandardScaler()
model = LogisticRegression()

# --- Training Data (dummy for now, replace later) ---
# Features: [income, expenses, savings, missed_payments]
X = np.array([
    [500, 300, 200, 0],
    [1000, 700, 300, 1],
    [200, 180, 20, 2],
    [800, 600, 200, 0],
    [1200, 800, 400, 1],
    [300, 250, 50, 3],
    [900, 400, 300, 0],
    [400, 350, 100, 2]
])

# Target: 1 = default, 0 = no default
y = np.array([0, 0, 1, 0, 0, 1, 0, 1])

# Scale features
X_scaled = scaler.fit_transform(X)

# Train model
model.fit(X_scaled, y)


# --- Feature engineering function ---
def prepare_features(income, expenses, savings, missed):
    # Avoid division by zero
    if income == 0:
        income = 1

    savings_ratio = savings / income
    expense_ratio = expenses / income

    return np.array([[income, expenses, savings, missed]])


# --- Prediction function ---
def predict_credit_score(income, expenses, savings, missed):

    # --- NORMALIZED METRICS ---
    savings_ratio = savings / income if income > 0 else 0
    expense_ratio = expenses / income if income > 0 else 1

    # --- SCORE COMPONENTS ---
    income_score = min(income / 5000, 1) * 25
    savings_score = min(savings_ratio, 1) * 25
    expense_score = max(0, (1 - expense_ratio)) * 25
    missed_penalty = missed * 10

    # --- FINAL SCORE ---
    score = income_score + savings_score + expense_score - missed_penalty

    # Clamp between 0 and 100
    score = max(0, min(100, score))

    # --- RISK CLASSIFICATION ---
    if score < 40:
        risk = "High"
    elif score < 70:
        risk = "Medium"
    else:
        risk = "Low"

    return {
        "score": round(score, 2),
        "risk": risk
    }

    # Simple explanation (important for trust)
    explanation = []

    if missed > 1:
        explanation.append("High missed payments")
    if expenses > income * 0.8:
        explanation.append("High expenses relative to income")
    if savings < income * 0.2:
        explanation.append("Low savings")

    if not explanation:
        explanation.append("Good financial behavior")

    return {
        "score": score,
        "risk": risk,
        "probability_default": float(prob_default),
        "explanation": explanation
    }