# -*- coding: utf-8 -*-
"""routes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E3QheykxcV_I3B9SM-lBNODd_4bv4yqV
"""

from flask import Blueprint, request, jsonify, render_template
from app.model import predict_credit_score

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/score', methods=['POST'])
def score():
    data = request.json

    score, risk, prob = predict_credit_score(
        float(data['income']),
        float(data['expenses']),
        float(data['savings']),
        float(data['missed_payments'])
    )

    return jsonify({
        "score": score,
        "risk": risk,
        "probability_default": prob
    })